# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Search-Z3950
version:      0.05
version_from: lib/Search/Z3950.pm
installdirs:  site
requires:
    MARC::Record:                  0
    Net::Z3950:                    0
    Net::Z3950::Manager:           0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
